name: Autotag
on:
  push:
    branches:
      - main
jobs:
  autotag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install
        run: curl -sL https://git.io/autotag-install | sh --
      - run: ./bin/autotag
      - run: git push --tags

  